### ISSUE TITLE
WifiWizard is not defined

### ISSUE THREAD

**Issue by joseangelmr** [parsonsmatt/ngWifiWizard#1]
Hi,

I'm using ngWifiWizard on my ionic app, but I have an error: WifiWizard is not defined,Why? is compatible with android ionic ngWifiWizard?. There is some demo or test with some example. Thank you

**Comment by parsonsmatt** [comment]
Hi Jose! These bindings were created for an older version of WifiWizard, and the demo is lost to history. I no longer do mobile/Android/Ionic development, and am unable to assist with this. You might want to try the main [`WifiWizard` repository](http://www.github.com/parsonsmatt/wifiwizard).
